### PR TITLE
Commit cabal file to allow projects to depend on git commits

### PR DESCRIPTION
**Pull request by seanhess**
Remove .cabal file from the .gitignore and commit to the repo. This allows one to depend on github branches via `source-repository-package`

```
-- cabal.project
source-repository-package
  type: git
  location: https://github.com/seanhess/fits-parse.git
  tag: 7828eb88957e2a93ffebf90974523dc4845a0c61
```

### CODE REVIEW

**Comment by seanhess** [comment]
Hey @krakrjak can we get this merged? It looks like the last PR hasn't been released on hackage, and I'd like to depend on your github in the meantime. Without this PR, I have to depend on my fork, even though the main repo has those changes merged

**Comment by krakrjak** [comment]
Yeah, give me the weekend to sort this out and cut a real release. The intention was to make a 0.4.0 release a while back and I just didn't get to it.

**Comment by krakrjak** [comment]
I'm not sure about this as the cabal file is generated and submitted as part of the src-dist.

What I want is the most compatible src layout for others to use, but this Cabal file is not suitable for uploading to hackage for inclusion in stackage. I have a special process to generate the src-dist package for upload.

Let me tinker with this and your suggestion about downstream cabal usage. I'll probably have more questions.

**Comment by krakrjak** [comment]
Maybe the right answer here for long-term support and ease of onboarding new users/developers is to drop the hpack usage completely and just give over to cabal + stack support. I think it's just time to transition to native cabal. It will also simplify release processes.

**Review by krakrjak — APPROVED** [review]
OK. It's settled. I'm accepting this merge and purging the package.yaml file and bumping the version to 0.4.0 in the upcoming PR.

**Comment by seanhess** [comment]
Sounds good!

**Pull request merged**
